server:
  port: 8081
  servlet:
      context-path: /usermgr
spring:
  application:
    name: usermgr-api-service
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_mgr?useUnicode=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
      # Redis服务器连接端口
    port: 6379
      # Redis服务器连接密码（默认为空）
    password: 123456
      # 连接池最大连接数（使用负值表示没有限制）
    pool:
      maxActive: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: -1
        # 连接池中的最大空闲连接
      maxIdle: 8
        # 连接池中的最小空闲连接
      minIdle: 0
      # 连接超时时间（毫秒）
      timeout: 0
        # 默认的数据过期时间，主要用于shiro权限管理
      expire: 2592000
#pagehelper分页配置
pagehelper:
      helperDialect: mysql
      reasonable: tr
      supportMethodsArguments: true
      params: count=countSql
